Spike data cleansing in flink
bptlab/cepta pull request #185
Opened 2020-03-24 11:21 UTC by ma-ro

This PR implements
-DataProvider for default  Java data types
-DataCleansing operator for default Java data types
-Tests for DataCleansing operator

2020-03-25 10:49 UTC, Quacck requested changes
yoink

2020-03-25 10:49 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataCleansingFunction.java
> +public class DataCleansingFunction {
Maybe we could use generics? :)

2020-03-25 10:49 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataCleansingFunction.java
> +    public static DataStream<Integer> cleanseStream(DataStream<Integer> InputStream, Integer FilterInteger) {
I think this wouldn't work well on our complex data types e.g. trainevents.

2020-03-25 10:49 UTC, Quacck commented on core/src/test/java/org/bptlab/cepta/data-cleansing-tests/DataCleansingTests.java
> +public class DataCleansingTests {
Please also test having a not-to-be-cleansed-value not getting cleansed

2020-03-26 10:25 UTC, ma-ro commented on core/src/main/java/org/bptlab/cepta/operators/DataCleansingFunction.java
> +public class DataCleansingFunction {
we do now!

2020-03-31 07:24 UTC, merged