261 postgres correlation
bptlab/cepta pull request #262
Opened 2020-05-04 16:33 UTC by skydivin4ng3l

Implements Lazy Schema creation for postgre dataToDatabase operator

2020-05-18 14:09 UTC, Quacck requested changes
Really nice so far :)

Also please ensure our CI kinda runs through

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataToMongoDB.java
> +        // System.out.println("INVOKE");
Is this comment still needed?

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataToMongoDB.java
> +        MongoCollection<Document> coll = database.getCollection(collection_name);
Lets not use abbreviations

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataToMongoDB.java
> +        //start the subscriber -> start querying timeout defaults to 60seconds
Why do we need to use subscribers here? We didn't have to when we implemented the postgres correlation last year. Maybe add a comment explaining that so we can use if for reference later

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataToMongoDB.java
> +        }
Please improve error handling or error logging. If its just logging, maybe add information for when (which input) it failed or why. Use our overall logger perhaps?

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataToPostgresDatabase.java
> +    String query = "CREATE TABLE public."+table_name+" ( ";
if we already supply the table_name, we might aswell supply the full name with the `public.`?

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataToPostgresDatabase.java
> +  }
this is a nice function :)

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataToPostgresDatabase.java
> +      QueryResult result = future.get();
As far as I can see, we dont do anything with this result. Do we send the query just to test whether the query is correct? How often is this query then sent (could this have overhead)?

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataToPostgresDatabase.java
> +      }
Should we log/print these errors? We could also give them more descriptive names

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataToPostgresDatabase.java
> +  public void insert(T dataSet)
There should be some kind of feedback whether the insertion was correct (not just observable through us via a print).
Since we are modifying a collection we could do it like Java's [Collection.add()](https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#add-E-) which returns a boolean that describes whether the underlying collection was modified.

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DelayShiftFunctionMongo.java
> +                            String.valueOf(liveTrainData.getTrainSectionId()),
is there a difference to `.toString()`?

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/utils/database/Mongo.java
> +                .applyConnectionString(new ConnectionString("mongodb://" + mongoConfig.getUser() + ":" + mongoConfig.getPassword() + "@" + mongoConfig.getHost() + ":" + mongoConfig.getPort() + "/?aut
split this up into multiple lines?

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/utils/database/Mongo.java
> +                .applyConnectionString(new ConnectionString("mongodb://" + mongoConfig.getUser() + ":" + mongoConfig.getPassword() + "@" + mongoConfig.getHost() + ":" + mongoConfig.getPort() + "/?aut
same as above

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/utils/database/Mongo.java
> +    private static CodecRegistry getCustomCodecRegistry() {
Maybe add a comment what this does?

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/utils/database/Mongo.java
> +            for (int backwardsIterator = documentList.size()-1; backwardsIterator >= 0; backwardsIterator--) {
I don't think we should use "Iterator" in the name when its not an iterator.
I guess just index or i could be fine, since the code already conveys that its going from end to start.

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/utils/database/Mongo.java
> +                }
Could we use a for_each here or similar?

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/utils/database/Util.java
> +//      System.out.println(entry.getKey() + "/" + entry.getValue());
Lets remove this comment if its not needed

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/utils/notification/NotificationHelper.java
> +        return Notification.newBuilder().setDelay(delayBuilder.build()).build();
Some formatting would be nice

2020-05-18 14:09 UTC, Quacck commented on core/src/test/java/org/bptlab/cepta/data-to-mongo-db/DataToMongoDBTests.java
> +    public void inputAmountOne() throws Exception {
We usually put a `test` in the testname. We should do that in this class too

2020-05-18 14:09 UTC, Quacck commented on core/src/test/java/org/bptlab/cepta/data-to-mongo-db/DataToMongoDBTests.java
> +    public void inputAmountOne() throws Exception {
Also maybe testInputtingOneValue?

2020-05-18 14:09 UTC, Quacck commented on core/src/test/java/org/bptlab/cepta/data-to-mongo-db/DataToMongoDBTests.java
> +    public void inputAmountMore() throws Exception {
maybe testInputtingMultipleValues?

2020-05-18 14:09 UTC, Quacck commented on core/src/test/java/org/bptlab/cepta/data-to-mongo-db/DataToMongoDBTests.java
> +        TestListResultSink<PlannedTrainData> sink = new TestListResultSink<>();
This is apparently never used?

2020-05-18 14:09 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/Main.java
> +>>>>>>> origin/dev
this kinda breaks the build :P

2020-05-18 14:09 UTC, Quacck commented on core/src/test/java/org/bptlab/cepta/delay-shift-mongo/DelayShiftFunctionMongoTests.java
> +        assertEquals(expectedNots, nots);
Abbreviations?

2020-05-18 14:09 UTC, Quacck commented on core/src/test/java/org/bptlab/cepta/delay-shift-mongo/DelayShiftFunctionMongoTests.java
> +        //MongoIterable<String> databases = mongoClient.listDatabaseNames();
remove?

2020-05-19 07:54 UTC, skydivin4ng3l commented on core/src/main/java/org/bptlab/cepta/operators/DataToMongoDB.java
> +        //start the subscriber -> start querying timeout defaults to 60seconds
The AsyncMongo Driver works with reactive Streams, so it provides Stream Providers, which we have to subscribe to to get the query executed. There should have been a comment, a link, but I will add another explaination

2020-05-19 07:55 UTC, skydivin4ng3l commented on core/src/main/java/org/bptlab/cepta/operators/DataToMongoDB.java
> +        MongoCollection<Document> coll = database.getCollection(collection_name);
yes, will do

2020-05-19 07:59 UTC, skydivin4ng3l commented on core/src/main/java/org/bptlab/cepta/operators/DataToPostgresDatabase.java
> +    String query = "CREATE TABLE public."+table_name+" ( ";
could be done if you wish so, but all Postgre is more or less deprecated. The idea was to keep it  simple, if everything is public.table it has more complexity as needed.

2020-05-19 08:01 UTC, skydivin4ng3l commented on core/src/test/java/org/bptlab/cepta/data-to-mongo-db/DataToMongoDBTests.java
> +    public void inputAmountMore() throws Exception {
is this a suggestion for a new test or a rename

2020-05-19 08:02 UTC, skydivin4ng3l commented on core/src/main/java/org/bptlab/cepta/Main.java
> +>>>>>>> origin/dev
lol?

2020-05-19 08:11 UTC, Quacck commented on core/src/test/java/org/bptlab/cepta/data-to-mongo-db/DataToMongoDBTests.java
> +    public void inputAmountMore() throws Exception {
just a rename

2020-05-19 18:35 UTC, Quacck approved these changes
Yo

2020-05-19 18:35 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DataToPostgresDatabase.java
> +  public void insert(T dataSet)
Added is as a todo

2020-05-19 18:35 UTC, Quacck commented on core/src/main/java/org/bptlab/cepta/operators/DelayShiftFunctionMongo.java
> +                            String.valueOf(liveTrainData.getTrainSectionId()),
(valueOf reads the primitive datatypes int long etc.)

2020-05-25 23:05 UTC, merged